### ISSUE TITLE
Scan directory with symbolic links

### ISSUE THREAD

**Issue by kaffka-k** [kornysietsma/polyglot-code-scanner#1]
I want to scan a directory with symbolic links to multiple git repos. The file tree looks something like this:
```
root
|-module-a
 |-.git 
|-module-b
 |-.git
```
I used  `.git` to show what directories are under git control. And the directories `module-a` and `module-b` are just symbolic links, because the build system works that way (and it's just an example in reality there are more than 50 of those modules).
It looks like symbolic links for folders are not followed. Is there a possibility to turn on following symbolic links?

**Comment by kornysietsma** [comment]
Sorry I missed this - when did Github stop making you automatically watch repos you create?
It's on my backlog now, shouldn't be too hard to add this as an option.
